
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: sistema_enquetes_development

test:
  <<: *default
  database: sistema_enquetes_test

production:
  primary: &primary_production
    <<: *default
    database: sistema_enquetes_production
    username: <%= ENV["DB_USERNAME"] %>
    password: <%= ENV["DB_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: sistema_enquetes_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: sistema_enquetes_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: sistema_enquetes_production_cable
    migrations_paths: db/cable_migrate
